### ISSUE TITLE
option tag

### ISSUE THREAD

**Issue by jesusgon4554** [bbrintle/project1#4]
I need to set the value of each option to its corresponding country and country code (as referenced in API). when I select one of the options I want that value to be stored in var currency and then URL + currency. not sure how to set that value..

**Comment by jesusgon4554** [comment]
HTML lines 36-40
JS Var lines

**Comment by bbrintle** [comment]
var amountToConvert = 0;
var amountInput = document.getElementById("amount");
var currencyElement = document.querySelector("option");
var selectCurrency = document.getElementById('CurrencyName');


function getSelectedOption(sel) {
    var opt;
    for ( var i = 0, len = sel.options.length; i < len; i++ ) {
        opt = sel.options[i];
        if ( opt.selected === true ) {
            break;
        }
    }
    return opt;
}

amountInput.addEventListener("change", function(){
    amountToConvert = amountInput.value;
    console.log(amountToConvert);
    var currencyID = getSelectedOption(selectCurrency)
    console.log(currencyID.value);
});

**Comment by bbrintle** [comment]
The code above should collect the amount the user puts in EVERY time it changes. It will also check and collect the value assigned by the selected location under CurrencyName.
